### ISSUE TITLE
Ideas regarding problems with fiat currencies

### ISSUE THREAD

**Issue by aaronduino** [SamuelBerman/CryptoTrader#1]
I see how moving around USD with an api would definitely be a problem.

Maybe we could buy (for example) bitcoin with (for example) doge-coin and convert that to USD separately. Or we could just keep it in doge-coin and sell manually when we feel like it.

Any ideas?

**Comment by SamuelBerman** [comment]
I think for now we can just trade between cryptocurrencies and not worry about fiat at all. Later we can try to add conversions using some API.

**Comment by aaronduino** [comment]
@SamuelBerman Yeah. Let's do that.

**Comment by aaronduino** [comment]
Should I close this issue?
